---
# apache playbook
apache_listen_port: 80
apache_remove_default_vhost: true
apache_vhosts:
 - servername: "dev"
   documentroot: "/var/www/webapp"

# mysql playbook
mysq_enabled_on_startup: yes
mysql_root_password: "{{ vault_mysql_root_password }}"

# php playbook
php_packages: [libapache2-mod-php5]
