---
- hosts: lamp
  user: vagrant
  become: true
  become_user: root
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
...
